### ISSUE TITLE
csexton action using old node.js v12

### ISSUE THREAD

**Issue by tekktrik** [circuitpython/circuitpython-unified-build-ci#4]
It's probably worth switching to a more regularly maintained action, like: https://github.com/shogo82148/actions-upload-release-asset

See https://github.com/adafruit/cookiecutter-adafruit-circuitpython/issues/208 for original idea by 2bndy5.

**Comment by 2bndy5** [comment]
https://github.com/csexton/release-asset-action/issues/20

**Comment by dunkmann00** [comment]
Another action that supports creating/updating releases and uploading assets to the release is https://github.com/softprops/action-gh-release. It is maintained and looks to be fairly widely used. I just started using it and am happy with it.

I have no connection to the action other than as a user, just thought it might be a good option for you to look into.

**Comment by 2bndy5** [comment]
The thing I didn't like about most other release asset actions is that the name of the release is changed to the tag name if not specified in the workflow. The shogo82148/actions-upload-release-asset doesn't appropriate the release's name.

EDIT: It looks like the softprops/action-gh-release won't appropriate release info (like name and body content) if a release is already associated with the given tag. This changed ([v0.1.6](https://github.com/softprops/action-gh-release/releases/tag/v0.1.6)) since I last tried it out (& after a year long maintenance hiatus).

**Comment by dunkmann00** [comment]
Correct, from the README:
> 💡 When the release info keys (such as name, body, draft, prerelease, etc.) are not explicitly set and there is already an existing release for the tag, the release will retain its original info.

**Comment by 2bndy5** [comment]
I guess the deciding factor then would be if the newer workflow should react to users pushing tags instead of (or in addition to) publishing a release via github's UI/CLI.

**Comment by tekktrik** [comment]
Closed via #11
